include:
  - compose-infra.yml

services:
  slideshow:
    image: slideshow/ggruzdov-demo-app:1.0
    container_name: slideshow
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_HOST=slideshow-db'
    depends_on:
      - postgres
    restart: always
