include:
  - compose-infra.yml

services:
  demo_nvs:
    image: nvs/ggruzdov-demo-app:1.0
    container_name: nvs-app
    ports:
      - '8080:8080'
    environment:
      - 'POSTGRES_HOST=nvs-db'
    depends_on:
      - postgres
    restart: always
