services:
  postgres:
    image: postgres:16.4
    container_name: nvs-db
    environment:
      - 'POSTGRES_DB=nvs'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=password'
    command: "-c log_statement=all"
    ports:
      - '5432:5432'
