spring:
  application:
    name: slideshow
  docker:
    compose:
      skip:
        in-tests: false
      stop:
        command: down
      file: compose-infra.yml
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/slideshow
    username: admin
    password: password
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true # Postgres will rewrite regular insert statements into multi-value ones for batched inserts.
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true # Hibernate will execute insert parent first and only then all the child inserts.
        order_updates: true
        id:
          optimizer:
            pooled:
              preferred: pooled-lo # to reduce the database round trip to get the ID(for batches)
#        generate_statistics: true

logging.level:
    org.hibernate:
#      SQL: DEBUG
#      type.descriptor.sql: TRACE
#      orm.jdbc.batch: TRACE