CREATE SEQUENCE IF NOT EXISTS images_id_seq START WITH 1 INCREMENT BY 10;

CREATE TABLE images
(
    id         BIGINT       NOT NULL,
    url        VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    duration   INTEGER      NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE proofs_of_play
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_id      BIGINT                                  NOT NULL,
    slide_show_id INTEGER                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_proofs_of_play PRIMARY KEY (id)
);

CREATE TABLE slide_shows
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active_image_id BIGINT                                   NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_slide_shows PRIMARY KEY (id)
);

CREATE TABLE slide_shows_images
(
    slide_show_id BIGINT NOT NULL,
    image_id      BIGINT NOT NULL,
    CONSTRAINT pk_slide_shows_images PRIMARY KEY (slide_show_id, image_id)
);

ALTER TABLE slide_shows
    ADD CONSTRAINT FK_SLIDE_SHOWS_ON_ACTIVEIMAGE FOREIGN KEY (active_image_id) REFERENCES images (id);

ALTER TABLE slide_shows_images
    ADD CONSTRAINT fk_slishoima_on_image FOREIGN KEY (slide_show_id) REFERENCES slide_shows (id);

ALTER TABLE slide_shows_images
    ADD CONSTRAINT fk_slishoima_on_slide_show FOREIGN KEY (image_id) REFERENCES images (id);

CREATE UNIQUE INDEX url_uidx ON images (url);
CREATE INDEX name_idx ON images (name);
CREATE INDEX image_id_idx ON slide_shows_images (image_id);
